language: node_js
node_js:
  - "6.10.0"
services:
  - postgresql
before_script:
  - psql -c 'create database photographer_test;' -U postgres
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
